
logging:
  level: debug
spring:
  datasource:
    name: quxue_voice
    url: jdbc:mysql://growtest.mysql.rds.aliyuncs.com:3306/kuaigrowth_dev?allowMultiQueries=true
    username: kuaigrowth_dev
    password: growth_dev123
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

    jpa:
      open-in-view: false

---

