logging:
  level: DEBUG

server:
 port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: file://E:/git/config-repo
        native:
          searchLocations: classpath:/shared
  application:
    name: piggy-config

  profiles:
    active: native


management:
  security:
   enabled: false

