logging:
  level: DEBUG

server:
 port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: file://E:/git/config-repo
        native:
          searchLocations: classpath:/shared
  application:
    name: piggy-config

  profiles:
    active: native

eureka:   #将其注册为config为一个服务,极其方便进行集群
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

management:
  security:
   enabled: false

